# Generated by Django 4.2.8 on 2024-01-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('route', models.CharField(max_length=30)),
                ('depo', models.CharField(max_length=30)),
                ('exit1', models.CharField(max_length=30)),
                ('exit2', models.CharField(max_length=30)),
                ('plan1', models.CharField(max_length=30)),
                ('plan2', models.CharField(max_length=30)),
                ('brak', models.CharField(max_length=30)),
                ('zader', models.CharField(max_length=30)),
                ('snizh_dkr_kr', models.CharField(max_length=30)),
                ('snizhskor', models.CharField(max_length=30)),
                ('pereklpotu', models.CharField(max_length=30)),
                ('itogo', models.CharField(max_length=30)),
                ('itogoproc', models.CharField(max_length=30)),
                ('flightwithoutplan', models.CharField(max_length=30)),
                ('srskor', models.CharField(max_length=30)),
                ('srskorplan', models.CharField(max_length=30)),
            ],
        ),
    ]
