# Generated by Django 4.2.8 on 2024-01-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metroApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metro',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
