# Generated by Django 4.2.8 on 2024-01-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metroApp', '0002_metro_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metro',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
