# Generated by Django 4.2.8 on 2024-01-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metroApp', '0003_alter_metro_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id_driver', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('tram_number', models.CharField(max_length=30)),
            ],
        ),
    ]
